seed: 2025

# input candidate artifacts from best lambda
train_candidate_ready_json: dataset/setting_a/15_posthoc_debias/best_lambda_artifacts/train_top20_drkgc_ready.json
valid_candidate_ready_json: dataset/setting_a/15_posthoc_debias/best_lambda_artifacts/valid_top20_drkgc_ready.json
test_candidate_ready_json: dataset/setting_a/15_posthoc_debias/best_lambda_artifacts/test_top20_drkgc_ready.json

# raw triples / graph
train_graph_tsv: dataset/setting_a/02_graph/train_enriched_deg1000_final.tsv
train_split_tsv: dataset/setting_a/01_split/train.tsv
valid_split_tsv: dataset/setting_a/01_split/valid.tsv
test_split_tsv: dataset/setting_a/01_split/test.tsv

# mappings
entity2id_path: dataset/setting_a/04_drkgc_json/entity2id.pkl
id2entity_path: dataset/setting_a/04_drkgc_json/id2entity.pkl
relation2id_path: dataset/setting_a/04_drkgc_json/relation2id.pkl
id2relation_path: dataset/setting_a/04_drkgc_json/id2relation.pkl

# prompt_subgraph resources
tail_pred_lex: dataset/setting_a/05_prompt_subgraph_subset/tail_prediction_lexicon.json
head_pred_lex: dataset/setting_a/05_prompt_subgraph_subset/head_prediction_lexicon.json
rules_path: dataset/setting_a/05_prompt_subgraph_subset/rules.json

# output
output_dir: dataset/setting_a/16_backbone_ready_posthoc_debias
report_dir: reports/week8

target_relation: indication
graph_size: 100
bkg: true